from termitype.app.app import App
from termitype.adapters.macos import MacAdapter
from termitype.core.engine import TypingEngine
from termitype.screens.sandbox import SandboxScreen
from termitype.screens.typingrun import TypingRunScreen
from termitype.screens.menu import MenuScreen
from termitype.screens.settings import SettingsScreen
from termitype.storage.settings import default_settings
from termitype.models.settings import DisplaySettings
from typing import List



def main():
    adapter = MacAdapter()

    settings = default_settings()
    display_settings = DisplaySettings.from_settings(settings)

    menu = MenuScreen(display_settings)

    engine = TypingEngine(words())

    menu.register_screen(id="r", view=TypingRunScreen(adapter, menu, engine, display_settings), description="Run test!")
    menu.register_screen(id="s", view=SettingsScreen(adapter, menu, display_settings), description="Settings")
    menu.register_screen(id="b", view=SandboxScreen(adapter, menu, display_settings), description="Sandbox")

    app = App(adapter, menu)

    try:
        adapter.startup()
        app.run()
    finally:
        adapter.finalize()


def words() -> List[str]:
    return [
        "the",
        "be",
        "of",
        "and",
        "a",
        "to",
        "in",
        "he",
        "have",
        "it",
        "that",
        "for",
        "they",
        "I",
        "with",
        "as",
        "not",
        "on",
        "she",
        "at",
        "by",
        "this",
        "we",
        "you",
        "do",
        "but",
        "from",
        "or",
        "which",
        "one",
        "would",
        "all",
        "will",
        "there",
        "say",
        "who",
        "make",
        "when",
        "can",
        "more",
        "if",
        "no",
        "man",
        "out",
        "other",
        "so",
        "what",
        "time",
        "up",
        "go",
        "about",
        "than",
        "into",
        "could",
        "state",
        "only",
        "new",
        "year",
        "some",
        "take",
        "come",
        "these",
        "know",
        "see",
        "use",
        "get",
        "like",
        "then",
        "first",
        "any",
        "work",
        "now",
        "may",
        "such",
        "give",
        "over",
        "think",
        "most",
        "even",
        "find",
        "day",
        "also",
        "after",
        "way",
        "many",
        "must",
        "look",
        "before",
        "great",
        "back",
        "through",
        "long",
        "where",
        "much",
        "should",
        "well",
        "people",
        "down",
        "own",
        "just",
        "because",
        "good",
        "each",
        "those",
        "feel",
        "seem",
        "how",
        "high",
        "too",
        "place",
        "little",
        "world",
        "very",
        "still",
        "nation",
        "hand",
        "old",
        "life",
        "tell",
        "write",
        "become",
        "here",
        "show",
        "house",
        "both",
        "between",
        "need",
        "mean",
        "call",
        "develop",
        "under",
        "last",
        "right",
        "move",
        "thing",
        "general",
        "school",
        "never",
        "same",
        "another",
        "begin",
        "while",
        "number",
        "part",
        "turn",
        "real",
        "leave",
        "might",
        "want",
        "point",
        "form",
        "off",
        "child",
        "few",
        "small",
        "since",
        "against",
        "ask",
        "late",
        "home",
        "interest",
        "large",
        "person",
        "end",
        "open",
        "public",
        "follow",
        "during",
        "present",
        "without",
        "again",
        "hold",
        "govern",
        "around",
        "possible",
        "head",
        "consider",
        "word",
        "program",
        "problem",
        "however",
        "lead",
        "system",
        "set",
        "order",
        "eye",
        "plan",
        "run",
        "keep",
        "face",
        "fact",
        "group",
        "play",
        "stand",
        "increase",
        "early",
        "course",
        "change",
        "help",
        "line"
    ]
